### ISSUE TITLE
host argument missing in example

### ISSUE THREAD

**Issue by afranck64** [osscameroon/broken_link_checker#37]
The following example in README.md and README-PYPI.md is missing the host argument and isn't running as is.

`python -m broken_link_checker https://example.com --delay 1`

**Comment by elhmn** [comment]
What is the appropriate way to run the program ?

**Comment by afranck64** [comment]
The host keyword, not argument I meant.
That would be:
`python -m broken_link_checker --host https://example.com --delay 1`

Implementing #38 will make this irrelevant.
