### ISSUE TITLE
Make host a non optional argument

### ISSUE THREAD

**Issue by afranck64** [osscameroon/broken_link_checker#38]
Most use cases if not all seem to require a host/url. Being able to pass the host without extra arguments would be nice.

**Comment by pythonbrad** [comment]
@afranck64 I don't understand very well your issue.
But, it's possible to pass arguments inside a file.

#### Configuration file (conf.ini)
```ini
[Checker]
host=https://example.com
delay=1

[Notifier]
sender=example@example.com
password=example
smtp_server=smtp.example.com:123
recipient=example@example.org
```

#### Usage
```bash
python3 -m broken_link_checker -c conf.ini
```

**Comment by pythonbrad** [comment]
> Most use cases if not all seem to require a host/url. Being able to pass the host without extra arguments would be nice.

Ok, i understand now. Actually we need to add the keyword "--host" in front. But host should not be optional.
